### PR TITLE
Added suggestion for newsboat

### PR DESCRIPTION
**Pull request by MindTooth**
This is a terminal RSS reader.
https://newsboat.org/

screen shot 2018-05-10 at 21 32 15
screen shot 2018-05-10 at 21 32 37

### CODE REVIEW

**Comment by roosta** [comment]
I'm a bit wary of adding app config to this repo, the reason I included all the terminal configs are because they are required to use vim-srcery in terminal. How about I make a repository called `srcery-contrib` and add you as a contributer? I have some configs I feel could benefit being associated with srcery as well.

**Comment by MindTooth** [comment]
Cool 👍  I'll contribute as much as possible.

What about `contrib-srcery`, `apps-srcery`, or something?  As you have `vim-srcery` and `emacs-srcery`.

I'm a total sucker for consistency xD  My head would crumble if they are in different order.  But I follow your command ;)

**Comment by roosta** [comment]
contrib-srcery is more consistent :) lets call it that.

**Comment by roosta** [comment]
Yeah, the folder structure makes sense, lets do that

**Comment by MindTooth** [comment]
What do you think about also adding `terminal`?  As kitty,putty,cygwin are terminal emulators, but ranger,newsboat,mutt, etc is for the `shell`?

**Comment by roosta** [comment]
Makes sense, I set it up like that with the init commit.

**Pull request closed without merging**
