### PR TITLE
Fix guifg color when transparent

### PR DESCRIPTION
**Pull request by MindTooth**
Just noticed.  Guess this needs fixed.

### CODE REVIEW

**Comment by roosta** [comment]
I think it should be like this: 
```vim
" Normal text
if g:srcery_transparent_background == 1
  call s:HL('Normal', s:bright_white, s:bg_black)
 else
   call s:HL('Normal', s:bright_white, s:black)
 endif
```
Setting the background color to none in GUI doesn't work.

**Comment by MindTooth** [comment]
Then the background won't be transparent in terminal.  _(I don't run GUI, but I'll fix that for future testing.)_

Then we need to check for gui/term.  The only way to have a transparent bg in terminal is to remove it, and we can't adjust opacity.

Maybe somthing like:
```vim
if g:srcery_transparent_background == 1 && !has("gui_running")
  call s:HL('Normal', s:bright_white, s:none
 else
  call s:HL('Normal', s:bright_white, s:black)
endif
```

**Comment by roosta** [comment]
But if you take a look at the bg_black var, it does just that. When in terminal it sets bg to none else it uses a defined hex

**Comment by MindTooth** [comment]
There you can see the issues.
screen shot 2018-05-14 at 12 49 24

However, I came to maybe realise that the error occurs because I have set `termguicolors`.  Disabling it fixes the issue.  How to then proceed?  The issue seems to only affect the background color, so maybe there is something when assigning that creates a incomplete variable.

_(I am sorry that I maybe leading you on a stray, but I am learning, and I've come to realise the pain of detecting all edge cases.)_

**Comment by roosta** [comment]
I see, I didn't know about the termguicolor option. Did not take that into account which Srcery totally should. Then your suggestion of using an extra check for GUI is the optimal solution I think, and then we get rid of the bg_black var.

**Comment by roosta** [comment]
Don't know why it works elsewhere tho, rather weird

**Comment by roosta** [comment]
I've pushed a fix to the develop branch, wanna check it out and see if it works for you?

**Comment by MindTooth** [comment]
The changes works great.  The option still needs to be set.  I think it's because when `termguicolor` is enabled, it looks for `guibg` to be set, and setting `ctermbg` does not do anything.  At least what my tiny test just confirmed.

I disabled the transparent option, and via the CLI entered the following:
```vim
hi Normal ctermbg=NONE (no changes)

hi Normal guibg=NONE (applied)
```
Also works in MacVim with `set transparency={0..100}`

**Comment by roosta** [comment]
Thats how I understood it as well. Glad the changes worked, but what do you mean the option still needs to be set? do you mean `termguicolor`? It works here regardless of that option.

**Comment by MindTooth** [comment]
The `g:srcery_transparent_background` variable.   I worked on the assumption that one could be forfeited, but that not true.  Dictating the background is and should be default before user intervention.

I like your changes, so I'll go ahead and close this 👍

**Pull request closed without merging**
